### ISSUE TITLE
新的EFI有问题

### ISSUE THREAD

**Issue by ghost** [LinZong/dell-inspiron-7590-hacktonish#13]
大佬更新HDMI输出的EFI之后，我系统就进不去了，加载完苹果LOGO之后就出现禁止通行的图标了，是不是有问题？

**Comment by LinZong** [comment]
这份EFI在10.15.2下测试通过。我觉得应该是只有10.15才包含了9代U核显正确的platform-id。建议你升级到10.15.2。
或者如果不想升级的话，先checkout回旧版本，点亮系统之后用新版config.plist替换旧的看看可不可以。手上没10.14暂时不能测试这种情况……

**Comment by ghost** [comment]
大佬怎么从10.14升级到10.15.2的

**Comment by LinZong** [comment]
> 大佬怎么从10.14升级到10.15.2的

需要全盘备份升10.15.2，不能直接从App Store升。
