### ISSUE TITLE
更换DW1820A网卡

### ISSUE THREAD

**Issue by ghost** [LinZong/dell-inspiron-7590-hacktonish#14]
想请教一下大佬，更换DW1820A网卡是不是要屏蔽针脚？我看网上很多都说要屏蔽

**Comment by wraptor** [comment]
我购买了黑果小兵闲鱼的1820A网卡，旧版本10.14的WIFI直接免驱能用，现在10.15版本，蓝牙能用，wifi点亮不了，按照黑果官网修改config也不能点亮

**Comment by LinZong** [comment]
Fixed at [#16 ](https://github.com/LinZong/dell-inspiron-7590-hackintosh/commit/a0b514e7a02accf8861380ef71883ac61819f854)
