### ISSUE TITLE
【10.15.2】请问大佬我装机的步骤是否正确，为什么我装不成功

### ISSUE THREAD

**Issue by wraptor** [LinZong/dell-inspiron-7590-hacktonish#15]
1.准备一个新的U盘
2.下载黑果小兵10.15.2提供的镜像
3.下载git最新的EFI
4.用balenaEtche将镜像写入U盘
5.进入WinPE将下载的EFI全部复制进去并覆盖重复的（没覆盖直接启动进入黑果镜像中的EFI，不会出现安装界面，会一直卡在一个黑屏命令行中）
6.进入U盘的CLOVER安装（第一个问题，安装的全部过程中，鼠标很灵敏但点击抹盘、下一步、键盘输入之类的这些非常卡）（多次都是）
7.抹除一个分区为AFPS
8.安装进这个分区（安装进度条未全部读完就自动重启了）（多次都是）
9.重启后CLOUVER中选择进入AFPS这个分区（进入后读条，未读完黑屏，然后出现错乱的读条界面，最后一直卡在这个步骤一个多小时）（多次都是）

**Comment by wraptor** [comment]
大佬我装完成了，可以进入mac系统了，但是整个界面操作非常卡，用的是最新的EFI，请问你有这种情况吗，或者说我还需要进行什么修改呢

**Comment by LinZong** [comment]
没有，我在10.14.6直接抹盘装10.15.2很正常。

**Comment by LinZong** [comment]
请问你这个卡，有没有表现在苹果图标读条的时候就已经很慢？

**Comment by wraptor** [comment]
对读条非常慢，而且还会花屏，然后一会又好了

**Comment by wraptor** [comment]
那请问我的步骤对不对呢，我也是重新抹盘装的，下载的是黑果提供的macOS Catalina 10.15.2(19C57) Installer for Clover 5100 and WEPE，然后用balenaEtche写入U盘，然后进PE将你的EFI覆盖到镜像中的EFI，然后进行安装，而在安装的界面操作的时候就已经非常卡了

**Comment by wraptor** [comment]
我是装在新买的海康威视固态c2000pro中，然后抹盘的格式是AFPS，请问应该不是这两的问题吧，毕竟安装的时候界面就很卡了，感觉是独显的问题

**Comment by LinZong** [comment]
步骤没问题，那你检查一下那个TSCync的kext在不在，如果不行先切回旧版本的EFI安装10.15.2

**Comment by wraptor** [comment]
切回2019-10-09 a5869c3这个版本吗，然后安装后再将最新版的EFI替换进去？

**Comment by wraptor** [comment]
我看了下，\EFI\CLOVER\kexts\Other\VoodooTSCSync_Release_v1.5.0.kext这个文件是存在的

**Comment by wraptor** [comment]
- -  大佬我切不回a5869c3这个版本，tools/CPU-S中有个文件的名字格式在windows不能用，所以总是报错，大佬你能不能把a5869c3这个版本的EFI打包发给我啊(xm_hhs@163.com)，不需要Tools这个文件夹，之前版本安装10.14是可以的这次安装10.15.2咋安装都不行，读条还总是花屏。。。

**Comment by wraptor** [comment]
大佬用linux回退到a5869c3这个版本了，然而这个EFI放进去后连进入到安装界面都不行，一直卡在读条那边

**Comment by LinZong** [comment]
你看一下邮箱，我们用QQ联系？

**Comment by wraptor** [comment]
安装成功，我的步骤有问题，按照大佬的演示已安装成功并进入系统，最终只差wifi的问题，购入1820A按照黑果的方法驱动失败了

**Comment by wraptor** [comment]
重新码一下正确的安装步骤吧
1.准备一个新的U盘
2.下载黑果小兵10.15.2提供的镜像
3.下载git最新的EFI（我在windows下克隆出错文件不完整，最终用Linux系统克隆并复制出EFI）
4.用balenaEtche将镜像写入U盘
5.进入WinPE或者用DiskGenius将原镜像中的EFI全部删除（必须删除），然后将7590的EFI复制进去
6.进入U盘的CLOVER安装（如果没有进bios新建一个启动项）

进入到安装界面不会卡说明一切正常了，然后照常安装就可以了
