### ISSUE TITLE
Dell 7590 fully working?

### ISSUE THREAD

**Issue by seyhadot** [LinZong/dell-inspiron-7590-hacktonish#17]
I want to buy Dell 7590 4k OLED and 32ram with 1tb ssd to install hackintosh but I don't know is everything is working fine , right?

**Comment by LinZong** [comment]
I had a 1080P model, it seems that there are some differences between 1080P and 4K. But there is an EFI for 4K model created by a guy. Hope it help. [Here](https://gitee.com/chtzs/Dell-Inspiron-7590-4k-Hackintosh)

**Comment by seyhadot** [comment]
thank you so much
