### ISSUE TITLE
请问网络连接的解决方案是什么

### ISSUE THREAD

**Issue by wraptor** [LinZong/dell-inspiron-7590-hacktonish#3]
请问如何使用WIFI和蓝牙，需要购买什么网卡吗？

**Comment by LinZong** [comment]
WIFI要么买USB，要么DW1830，DW1560
蓝牙的话买了DW1830顺带解决
有线连接买个小米的USB转RJ45比较经济实惠
因为DA300的网卡在苹果下没驱动

**Comment by wraptor** [comment]
购买DW1830的话是可以将现有的无线网卡换下来吗？还是需要占据一个固态m2接口
另外请问输入法切换的快捷键是？我一直切换不了
然后现在唯一的问题是hdmi输出不了吗
我试了下插入hdmi就自动重启，然后通过typec扩展坞的hdmi也是自动重启

**Comment by LinZong** [comment]
1. 对，购买DW1830需要更换当前无线网卡下来
2. 切换输入法是Control + 空格
3. 是啊HDMI烦死我了

**Comment by LinZong** [comment]
另外请检查Shortcuts里面的设置是否正确
![Screen Shot 2019-10-04 at 20 24 41](https://user-images.githubusercontent.com/10548832/66207367-2c800f00-e6e5-11e9-9c2c-e3b0ea3df075.png)

**Comment by Skimige** [comment]
DW1820A：我不配吗？

**Comment by wraptor** [comment]
dw1830太贵且很多都没货，闲鱼找黑果小兵买了个dw1820A加运费共72，换上后，windows需要安装驱动，mac的wifi蓝牙直接能用，把蓝牙文件拖进efi里airdrop也能用了，感觉dw1820A性价比还是可以的对比1830和1560等高价
