### ISSUE TITLE
关于HDMI输出

### ISSUE THREAD

**Issue by wraptor** [LinZong/dell-inspiron-7590-hacktonish#4]
请问大佬，这篇你有看过吗，貌似可以解决HDMI输出问题，我看了奈何看不懂 - -
教程：利用Hackintool打开第8代核显HDMI/DVI输出的正确姿势
https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

**Comment by LinZong** [comment]
看过，不能解决。理由是因为要么一插上HDMI线马上重启，根本看不到Connector里面有接口的颜色变化，要么Connector列表完全没反应。

**Comment by LinZong** [comment]
目前HDMI输出已经正常。
