### ISSUE TITLE
外放正常，耳机无声音

### ISSUE THREAD

**Issue by wraptor** [LinZong/dell-inspiron-7590-hacktonish#5]
步骤:
1.备份系统原版AppleHDA
sudo cp -R /System/Library/Extensions/AppleHDA.kext .

2.运行AppleHDAPatcher工具，拖入先前备份出来的原版AppleHDA
选择Laptop -> ALC 295
点击Patch
完成后会在桌面生成MironeAudio文件夹

3.替换系统原版AppleHDA
sudo cp -R ~/Desktop/MironeAudio/10ec0295/282.54/full Patched AppleHDA/AppleHDA.kext /System/Library/Extensions
# 10ec0295 和 282.54可能因人而异，需要根据实际情况替换。
sudo kextcache -i /
等待系统重建缓存完成

4.修改config.plist
首先确保ACPI设置中FixHDA, AddHDMI的勾选全部去掉，并且System IRQ修复已经应用（本仓库的config.plist已经完成此设置）

5.然后DSDT补丁中添加一行（本仓库config.plist已完成设置）
Rename HDAS to HDEF, Find=48444153, Replace=48444546

6."设备设置"中，Audio注入No，右边两个勾不要选。
根据目前最新的AppleALC官方usage, 目前AppleALC已经不再使用设备设置来Inject，
需要在下面的Properties中注入layout-id。本仓库的config.plist已经默认在PciRoot(0x0)/Pci(0x1f,0x3)上注入layout-id=77。

6.重启电脑，目的是让Rename HDAS to HDEF被应用, 然后打开终端，分别输入
kextstat | grep AppleHDA
kextstat | grep AppleALC
确保AppleALC前面的序号在AppleHDA之前。（AppleALC必须在AppleHDA之前被加载）

6.使用gfxutil获取HDEF设备的PciRoot
./gfxutil -f HDEF
记下DevicePath, 替换掉config.plist的Properties中的值，至于layout-id可以在13，28，77中来回试。默认AppleHDAPatch推荐的2和3对于戴尔来说都是不能用的。

6.重启电脑。查看声音输出是否正常。

7.借助macOS的Automator，在每次用户登录的时候正声卡输出。hda-verb工具以及生成的动作App已经附在Repo中。
hda-verb 0x19 0x707 0x20
首先尝试在终端下输入以上命令, 完成后插入耳机，平衡调到中间，测试耳机是否已经正常。如果正常，请继续操作，否则跳过下面全部设置，并上网找资料。

以下操作假设hda-verb在/User/<your-user-name>/目录下**
打开Automator, 选择"应用程序"
左侧任务列表中选择"运行Shell脚本"
右边空白文本区域输入
cd ~
./hda-verb 0x19 0x707 0x20
起英文名保存在一个容易发现的地方

8.系统偏好设置->用户与群组->登录项，添加刚才保存的App即可。
如果不出意外，每次登陆右上角通知Icon区域将会有小齿轮转1s左右，表明已经执行此命令纠正声卡输出。
如果您的电脑从睡眠中唤醒后发现声音又不正常了，请再次执行先前生成的App即可。笔者承认这样做确实很不优雅，但是笔者已经尝试在SSDT-ALC295.dsl里面加入自动使CodecCommander执行上述verb的Custom Command了但是它就是不work。如果有人知道原因还请不吝赐教。

**Comment by wraptor** [comment]
关于解决方案，我第三步已经做完了，按照提供的EFI，应该4和5也完成了，然后第六步就看不懂了，“设备设置“指的是什么呢？

**Comment by LinZong** [comment]
请问你的电脑用此EFI引导入系统之后喇叭是灰色的吗？

**Comment by LinZong** [comment]
教程的意思是截图中鼠标高亮选中的layout-id 77
![Screen Shot 2019-10-08 at 20 33 09](https://user-images.githubusercontent.com/10548832/66395822-f60b0280-ea0a-11e9-8660-9c047aaf02c2.png)

**Comment by wraptor** [comment]
![QQ20191008-203727](https://user-images.githubusercontent.com/52092701/66396114-9eb96200-ea0b-11e9-856f-f8f25001130e.png)
是有显示出插入耳机的，而且刚开始会有声音，1秒后就没了。
另外你这个图是什么软件的啊

**Comment by LinZong** [comment]
Clover Configurator, 打开config.plist

尝试使用hda-verb软件，在terminal下执行hda-verb 0x19 0x707 0x20看看是否能修复，如果能，直接跳到制作自启动修复工具

**Comment by wraptor** [comment]
大佬我又来了，在第六步的时候确保了ALC在HDA之前了，如下：
MacBook-Pro:~ huanghs$ kextstat | grep AppleHDA
  138    1 0xffffff7f81d91000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (282.54) E00FE0E4-B03D-34C5-8DC9-39C7D8D50B6B <137 69 44 13 8 7 6 5 3 1>
  155    0 0xffffff7f81f23000 0xb7000    0xb7000    com.apple.driver.AppleHDA (282.54) 88BFC11D-179D-3546-A3C9-B542C9127590 <154 138 137 70 69 44 7 6 5 3 1>
MacBook-Pro:~ huanghs$ kextstat | grep AppleALC
   47    0 0xffffff7f8338b000 0x120000   0x120000   as.vit9696.AppleALC (1.4.1) 643175DA-A09A-3A9A-9C1C-3C0A8A573B85 <37 13 8 6 5 3 2 1>

然后到了./gfxutil -f HDEF这一步，但是执行后，提示-bash: ./gfxutil: No such file or directory

**Comment by wraptor** [comment]
大佬niubi，直接下载hda-verb软件，解压后进入执行./hda-verb 0x19 0x707 0x20搞定了

**Comment by LinZong** [comment]
恭喜
