### ISSUE TITLE
关于EFI

### ISSUE THREAD

**Issue by ghost** [LinZong/dell-inspiron-7590-hacktonish#6]
大佬，我想问一下，我已经装好了黑苹果的，我能不能直接替换成你的EFI文件

**Comment by LinZong** [comment]
可以的，此EFI不区分安装和日用。

**Comment by ghost** [comment]
@LinZong 触摸板怎么样才算正常，没用过苹果的触摸板不太清楚这个，我现在替换了你的EFI文件之后，触摸板可以用了，但是再finder里面双指点击触摸板，没有出现右键菜单，但是在桌面正常的，这算触摸板驱动不正常吗？？

**Comment by LinZong** [comment]
> @LinZong 触摸板怎么样才算正常，没用过苹果的触摸板不太清楚这个，我现在替换了你的EFI文件之后，触摸板可以用了，但是再finder里面双指点击触摸板，没有出现右键菜单，但是在桌面正常的，这算触摸板驱动不正常吗？？

苹果的触摸板是不区分左右按键的，就一个板单指按是左键单击，双指是右键，普通笔记本模拟不了的，只能是目前这个样子。
