### ISSUE TITLE
关于mac下的散热问题

### ISSUE THREAD

**Issue by wraptor** [LinZong/dell-inspiron-7590-hacktonish#7]
首先cpu是i7-9750H的，mac系统关于里看是i9啥的，不知道有没有影响。
其次显卡UHD630，显示显存1500+MB，也不知道这个有没有影响。

主要是，使用过程中电脑热度比win下高挺多，F8按键范围旁甚至烫手，并且风扇好像是一直都没有转动的。不知道mac有没有散热管理啥的，温度会不会过高损坏硬件

**Comment by choucaicai** [comment]
我也想问...

**Comment by LinZong** [comment]
目前因为Mojave还没有正式支持9代U，所以为了过渡，只能选择了MBP2018版本，那个机型CPU是i9, 所以就显示成i9，如果不喜欢可以自行去论坛找如何改CPU型号的教程。

另外，本EFI直接使用的是MBP的变频策略，应该知道MBP这种东西除非很热了否则都不太喜欢转风扇的，所以风扇就是这样的。如果不喜欢这个策略可以用CPUFriend自定义变频策略。F8烫手那是肯定的，我在Win下比在Mac下更加烫手……
